# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Learning Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_leanrningDialog(object):
    def setupUi(self, leanrningDialog):
        leanrningDialog.setObjectName("leanrningDialog")
        leanrningDialog.resize(794, 502)
        self.verticalLayout = QtWidgets.QVBoxLayout(leanrningDialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topFrame = QtWidgets.QFrame(leanrningDialog)
        self.topFrame.setMaximumSize(QtCore.QSize(16777215, 40))
        self.topFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.topFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topFrame.setObjectName("topFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.topFrame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.topLeftFrame = QtWidgets.QFrame(self.topFrame)
        self.topLeftFrame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.topLeftFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.topLeftFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topLeftFrame.setObjectName("topLeftFrame")
        self.horizontalLayout.addWidget(self.topLeftFrame)
        self.topRightFrame = QtWidgets.QFrame(self.topFrame)
        self.topRightFrame.setMaximumSize(QtCore.QSize(80, 16777215))
        self.topRightFrame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.topRightFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.topRightFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topRightFrame.setObjectName("topRightFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.topRightFrame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.menuBtn = QtWidgets.QPushButton(self.topRightFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuBtn.sizePolicy().hasHeightForWidth())
        self.menuBtn.setSizePolicy(sizePolicy)
        self.menuBtn.setStyleSheet("border:1px sold;\n"
"QPushButton{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0,0,0);\n"
"}")
        self.menuBtn.setObjectName("menuBtn")
        self.verticalLayout_2.addWidget(self.menuBtn)
        self.horizontalLayout.addWidget(self.topRightFrame)
        self.verticalLayout.addWidget(self.topFrame)
        self.bottomFrame = QtWidgets.QFrame(leanrningDialog)
        self.bottomFrame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.bottomFrame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.bottomFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bottomFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottomFrame.setObjectName("bottomFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.bottomFrame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.bottomLeftFrame = QtWidgets.QFrame(self.bottomFrame)
        self.bottomLeftFrame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.bottomLeftFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottomLeftFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottomLeftFrame.setObjectName("bottomLeftFrame")
        self.pagesWidget = QtWidgets.QStackedWidget(self.bottomLeftFrame)
        self.pagesWidget.setGeometry(QtCore.QRect(50, 30, 611, 381))
        self.pagesWidget.setObjectName("pagesWidget")
        self.page1 = QtWidgets.QWidget()
        self.page1.setObjectName("page1")
        self.pagesWidget.addWidget(self.page1)
        self.page2 = QtWidgets.QWidget()
        self.page2.setObjectName("page2")
        self.pagesWidget.addWidget(self.page2)
        self.horizontalLayout_2.addWidget(self.bottomLeftFrame)
        self.ButtomRight = QtWidgets.QFrame(self.bottomFrame)
        self.ButtomRight.setMaximumSize(QtCore.QSize(80, 16777215))
        self.ButtomRight.setStyleSheet("alternate-background-color: rgb(255, 255, 255);")
        self.ButtomRight.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ButtomRight.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ButtomRight.setObjectName("ButtomRight")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.ButtomRight)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.ButtomRight)
        self.label_2.setMinimumSize(QtCore.QSize(0, 30))
        self.label_2.setStyleSheet("border:1px solid;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.addModule1Btn = QtWidgets.QPushButton(self.ButtomRight)
        self.addModule1Btn.setMinimumSize(QtCore.QSize(0, 30))
        self.addModule1Btn.setStyleSheet("QPushButton{    \n"
"color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"border:0px solid;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0,0,0);\n"
"}")
        self.addModule1Btn.setObjectName("addModule1Btn")
        self.verticalLayout_3.addWidget(self.addModule1Btn)
        self.addModule2Btn = QtWidgets.QPushButton(self.ButtomRight)
        self.addModule2Btn.setMinimumSize(QtCore.QSize(0, 30))
        self.addModule2Btn.setAutoFillBackground(False)
        self.addModule2Btn.setStyleSheet("QPushButton{    \n"
"color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"border:0px solid;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0,0,0);\n"
"}")
        self.addModule2Btn.setObjectName("addModule2Btn")
        self.verticalLayout_3.addWidget(self.addModule2Btn)
        self.subLabel = QtWidgets.QLabel(self.ButtomRight)
        self.subLabel.setMinimumSize(QtCore.QSize(0, 30))
        self.subLabel.setStyleSheet("border:1px solid;")
        self.subLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.subLabel.setObjectName("subLabel")
        self.verticalLayout_3.addWidget(self.subLabel)
        self.subModule1Btn = QtWidgets.QPushButton(self.ButtomRight)
        self.subModule1Btn.setMinimumSize(QtCore.QSize(0, 30))
        self.subModule1Btn.setStyleSheet("QPushButton{    \n"
"color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"border:0px solid;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0,0,0);\n"
"}")
        self.subModule1Btn.setObjectName("subModule1Btn")
        self.verticalLayout_3.addWidget(self.subModule1Btn)
        self.subModule2Btn = QtWidgets.QPushButton(self.ButtomRight)
        self.subModule2Btn.setMinimumSize(QtCore.QSize(0, 30))
        self.subModule2Btn.setStyleSheet("QPushButton{    \n"
"color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"border:0px solid;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0,0,0);\n"
"}")
        self.subModule2Btn.setObjectName("subModule2Btn")
        self.verticalLayout_3.addWidget(self.subModule2Btn)
        self.horizontalLayout_2.addWidget(self.ButtomRight, 0, QtCore.Qt.AlignTop)
        self.verticalLayout.addWidget(self.bottomFrame)

        self.retranslateUi(leanrningDialog)
        self.pagesWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(leanrningDialog)

    def retranslateUi(self, leanrningDialog):
        _translate = QtCore.QCoreApplication.translate
        leanrningDialog.setWindowTitle(_translate("leanrningDialog", "Learning Dialog"))
        self.menuBtn.setText(_translate("leanrningDialog", "Menu"))
        self.label_2.setText(_translate("leanrningDialog", "Addition"))
        self.addModule1Btn.setText(_translate("leanrningDialog", "Module1"))
        self.addModule2Btn.setText(_translate("leanrningDialog", "Module2"))
        self.subLabel.setText(_translate("leanrningDialog", "Subtraction"))
        self.subModule1Btn.setText(_translate("leanrningDialog", "Module1"))
        self.subModule2Btn.setText(_translate("leanrningDialog", "Module2"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     leanrningDialog = QtWidgets.QDialog()
#     ui = Ui_leanrningDialog()
#     ui.setupUi(leanrningDialog)
#     leanrningDialog.show()
#     sys.exit(app.exec_())
