# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resultscreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 600)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 500))
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(185, 189, 189);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TopBar = QtWidgets.QFrame(self.centralwidget)
        self.TopBar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.TopBar.setStyleSheet("background-color: rgb(116, 118, 118);\n"
"background-color: rgb(133, 136, 136);")
        self.TopBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TopBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TopBar.setObjectName("TopBar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.TopBar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_toggle = QtWidgets.QFrame(self.TopBar)
        self.frame_toggle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_toggle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_toggle.setObjectName("frame_toggle")
        self.horizontalLayout.addWidget(self.frame_toggle)
        self.frame_top = QtWidgets.QFrame(self.TopBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_top.sizePolicy().hasHeightForWidth())
        self.frame_top.setSizePolicy(sizePolicy)
        self.frame_top.setMaximumSize(QtCore.QSize(70, 40))
        self.frame_top.setStyleSheet("background-color: rgb(92, 190, 255);")
        self.frame_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_top)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.BtnToggle = QtWidgets.QPushButton(self.frame_top)
        self.BtnToggle.setStyleSheet("border: 0px")
        self.BtnToggle.setObjectName("BtnToggle")
        self.horizontalLayout_3.addWidget(self.BtnToggle)
        self.horizontalLayout.addWidget(self.frame_top)
        self.verticalLayout.addWidget(self.TopBar)
        self.Content = QtWidgets.QFrame(self.centralwidget)
        self.Content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Content.setObjectName("Content")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Content)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.FramePages = QtWidgets.QFrame(self.Content)
        self.FramePages.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FramePages.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FramePages.setObjectName("FramePages")
        self.frame_right_menu = QtWidgets.QFrame(self.FramePages)
        self.frame_right_menu.setGeometry(QtCore.QRect(930, 0, 70, 132))
        self.frame_right_menu.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame_right_menu.setStyleSheet("background-color: rgb(116, 118, 118);\n"
"")
        self.frame_right_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_right_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_right_menu.setObjectName("frame_right_menu")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_right_menu)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_top_menu = QtWidgets.QFrame(self.frame_right_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_top_menu.sizePolicy().hasHeightForWidth())
        self.frame_top_menu.setSizePolicy(sizePolicy)
        self.frame_top_menu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_menu.setObjectName("frame_top_menu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_top_menu)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Btn_Menu_1 = QtWidgets.QPushButton(self.frame_top_menu)
        self.Btn_Menu_1.setMinimumSize(QtCore.QSize(0, 40))
        self.Btn_Menu_1.setMaximumSize(QtCore.QSize(16777213, 16777215))
        self.Btn_Menu_1.setStyleSheet("QPushButton {\n"
" color: rgb(255, 255, 255);\n"
" background-color: rgb(116, 118, 118);\n"
" border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
" background-color: rgb(85, 170, 255);\n"
"}")
        self.Btn_Menu_1.setObjectName("Btn_Menu_1")
        self.verticalLayout_3.addWidget(self.Btn_Menu_1)
        self.Btn_Menu_4 = QtWidgets.QPushButton(self.frame_top_menu)
        self.Btn_Menu_4.setMinimumSize(QtCore.QSize(0, 40))
        self.Btn_Menu_4.setStyleSheet("QPushButton {\n"
" color: rgb(255, 255, 255);\n"
" background-color: rgb(116, 118, 118);\n"
" border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
" background-color: rgb(85, 170, 255);\n"
"}")
        self.Btn_Menu_4.setObjectName("Btn_Menu_4")
        self.verticalLayout_3.addWidget(self.Btn_Menu_4)
        self.Btn_Menu_3 = QtWidgets.QPushButton(self.frame_top_menu)
        self.Btn_Menu_3.setMinimumSize(QtCore.QSize(0, 40))
        self.Btn_Menu_3.setStyleSheet("QPushButton {\n"
" color: rgb(255, 255, 255);\n"
" background-color: rgb(116, 118, 118);\n"
" border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
" background-color: rgb(85, 170, 255);\n"
"}")
        self.Btn_Menu_3.setObjectName("Btn_Menu_3")
        self.verticalLayout_3.addWidget(self.Btn_Menu_3)
        self.Btn_Menu_2 = QtWidgets.QPushButton(self.frame_top_menu)
        self.Btn_Menu_2.setMinimumSize(QtCore.QSize(0, 40))
        self.Btn_Menu_2.setStyleSheet("QPushButton {\n"
" color: rgb(255, 255, 255);\n"
" background-color: rgb(116, 118, 118);\n"
" border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
" background-color: rgb(85, 170, 255);\n"
"}")
        self.Btn_Menu_2.setObjectName("Btn_Menu_2")
        self.verticalLayout_3.addWidget(self.Btn_Menu_2)
        self.verticalLayout_2.addWidget(self.frame_top_menu, 0, QtCore.Qt.AlignTop)
        self.Pages_Widget = QtWidgets.QStackedWidget(self.FramePages)
        self.Pages_Widget.setGeometry(QtCore.QRect(50, 60, 851, 421))
        self.Pages_Widget.setStyleSheet("background-color: rgb(163, 255, 205);\n"
"background-color: rgb(157, 190, 255);")
        self.Pages_Widget.setObjectName("Pages_Widget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.Pages_Widget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.Pages_Widget.addWidget(self.page_2)
        self.horizontalLayout_2.addWidget(self.FramePages)
        self.verticalLayout.addWidget(self.Content)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.BtnToggle.setText(_translate("MainWindow", "Menu"))
        self.Btn_Menu_1.setText(_translate("MainWindow", "Question1"))
        self.Btn_Menu_4.setText(_translate("MainWindow", "Question2"))
        self.Btn_Menu_3.setText(_translate("MainWindow", "Question3"))
        self.Btn_Menu_2.setText(_translate("MainWindow", "Question4"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
